-- Auto-generated TBC pet ability data (Petopia costs)
HunterPetTrainerData = HunterPetTrainerData or {}
local D = HunterPetTrainerData

D.MAX_ACTIVE = 4

D.Abilities = {
  ["Arcane Resistance"] = {
    active = false,
    families = { "ALL" },
    ranks = {
      [1] = { level = 20, cost = 5 },
      [2] = { level = 30, cost = 15 },
      [3] = { level = 40, cost = 45 },
      [4] = { level = 50, cost = 90 },
      [5] = { level = 60, cost = 105 },
    },
  },
  ["Avoidance"] = {
    active = false,
    families = { "ALL" },
    ranks = {
      -- Pet book lists these as "Passive" with no rank number; tipMatch identifies them.
      [1] = { level = 30, cost = 15, tipMatch = "25%%" },
      [2] = { level = 60, cost = 25, tipMatch = "50%%" },
    },
  },
  ["Bite"] = {
    active = true,
    families = { "Bat", "Bear", "Boar", "Carrion Bird", "Cat", "Crocolisk", "Dragonhawk", "Gorilla", "Hyena", "Nether Ray", "Raptor", "Ravager", "Serpent", "Spider", "Tallstrider", "Turtle", "Warp Stalker", "Wind Serpent", "Wolf" },
    ranks = {
      [1] = { level = 1, cost = 1 },
      [2] = { level = 8, cost = 4 },
      [3] = { level = 16, cost = 7 },
      [4] = { level = 24, cost = 10 },
      [5] = { level = 32, cost = 13 },
      [6] = { level = 40, cost = 17 },
      [7] = { level = 48, cost = 21 },
      [8] = { level = 56, cost = 25 },
      [9] = { level = 64, cost = 29 },
    },
  },
  ["Charge"] = {
    active = true,
    families = { "Boar" },
    ranks = {
      [1] = { level = 1, cost = 5 },
      [2] = { level = 12, cost = 9 },
      [3] = { level = 24, cost = 13 },
      [4] = { level = 36, cost = 17 },
      [5] = { level = 48, cost = 25 },
      [6] = { level = 60, cost = 29 },
    },
  },
  ["Claw"] = {
    active = true,
    families = { "Bear", "Carrion Bird", "Cat", "Crab", "Owl", "Raptor", "Scorpid", "Warp Stalker" },
    ranks = {
      [1] = { level = 1, cost = 1 },
      [2] = { level = 8, cost = 4 },
      [3] = { level = 16, cost = 7 },
      [4] = { level = 24, cost = 10 },
      [5] = { level = 32, cost = 13 },
      [6] = { level = 40, cost = 17 },
      [7] = { level = 48, cost = 21 },
      [8] = { level = 56, cost = 25 },
      [9] = { level = 64, cost = 29 },
    },
  },
  ["Cobra Reflexes"] = {
    active = false,
    families = { "ALL" },
    ranks = {
      [1] = { level = 30, cost = 15 },
    },
  },
  ["Cower"] = {
    active = true,
    families = { "ALL" },
    ranks = {
      [1] = { level = 5, cost = 8 },
      [2] = { level = 15, cost = 10 },
      [3] = { level = 25, cost = 12 },
      [4] = { level = 35, cost = 14 },
      [5] = { level = 45, cost = 16 },
      [6] = { level = 55, cost = 18 },
      [7] = { level = 65, cost = 21 },
    },
  },
  ["Dash"] = {
    active = true,
    families = { "Boar", "Cat", "Hyena", "Raptor", "Ravager", "Tallstrider", "Wolf" },
    ranks = {
      [1] = { level = 30, cost = 15 },
      [2] = { level = 40, cost = 20 },
      [3] = { level = 50, cost = 25 },
    },
  },
  ["Dive"] = {
    active = true,
    families = { "Bat", "Carrion Bird", "Dragonhawk", "Nether Ray", "Owl", "Wind Serpent" },
    ranks = {
      [1] = { level = 30, cost = 15 },
      [2] = { level = 40, cost = 20 },
      [3] = { level = 50, cost = 25 },
    },
  },
  ["Fire Breath"] = {
    active = true,
    families = { "Dragonhawk" },
    ranks = {
      [1] = { level = 1, cost = 5 },
      [2] = { level = 60, cost = 25 },
    },
  },
  ["Fire Resistance"] = {
    active = false,
    families = { "ALL" },
    ranks = {
      [1] = { level = 20, cost = 5 },
      [2] = { level = 30, cost = 15 },
      [3] = { level = 40, cost = 45 },
      [4] = { level = 50, cost = 90 },
      [5] = { level = 60, cost = 105 },
    },
  },
  ["Frost Resistance"] = {
    active = false,
    families = { "ALL" },
    ranks = {
      [1] = { level = 20, cost = 5 },
      [2] = { level = 30, cost = 15 },
      [3] = { level = 40, cost = 45 },
      [4] = { level = 50, cost = 90 },
      [5] = { level = 60, cost = 105 },
    },
  },
  ["Furious Howl"] = {
    active = true,
    families = { "Wolf" },
    ranks = {
      [1] = { level = 10, cost = 10 },
      [2] = { level = 24, cost = 15 },
      [3] = { level = 40, cost = 20 },
      [4] = { level = 56, cost = 25 },
    },
  },
  ["Gore"] = {
    active = true,
    families = { "Boar", "Ravager" },
    ranks = {
      [1] = { level = 1, cost = 1 },
      [2] = { level = 8, cost = 4 },
      [3] = { level = 16, cost = 7 },
      [4] = { level = 24, cost = 10 },
      [5] = { level = 32, cost = 13 },
      [6] = { level = 40, cost = 17 },
      [7] = { level = 48, cost = 21 },
      [8] = { level = 56, cost = 25 },
      [9] = { level = 63, cost = 29 },
    },
  },
  ["Great Stamina"] = {
    active = false,
    families = { "ALL" },
    ranks = {
      [1] = { level = 10, cost = 5 },
      [2] = { level = 12, cost = 10 },
      [3] = { level = 18, cost = 15 },
      [4] = { level = 24, cost = 25 },
      [5] = { level = 30, cost = 50 },
      [6] = { level = 36, cost = 75 },
      [7] = { level = 42, cost = 100 },
      [8] = { level = 48, cost = 125 },
      [9] = { level = 54, cost = 150 },
      [10] = { level = 60, cost = 185 },
      [11] = { level = 70, cost = 215 },
    },
  },
  ["Growl"] = {
    active = true,
    families = { "ALL" },
    ranks = {
      [1] = { level = 1, cost = 0 },
      [2] = { level = 10, cost = 0 },
      [3] = { level = 20, cost = 0 },
      [4] = { level = 30, cost = 0 },
      [5] = { level = 40, cost = 0 },
      [6] = { level = 50, cost = 0 },
      [7] = { level = 60, cost = 0 },
      [8] = { level = 70, cost = 0 },
    },
  },
  ["Lightning Breath"] = {
    active = true,
    families = { "Wind Serpent" },
    ranks = {
      [1] = { level = 1, cost = 1 },
      [2] = { level = 12, cost = 5 },
      [3] = { level = 24, cost = 10 },
      [4] = { level = 36, cost = 15 },
      [5] = { level = 48, cost = 20 },
      [6] = { level = 60, cost = 25 },
    },
  },
  ["Natural Armor"] = {
    active = false,
    families = { "ALL" },
    ranks = {
      [1] = { level = 10, cost = 1 },
      [2] = { level = 12, cost = 5 },
      [3] = { level = 18, cost = 10 },
      [4] = { level = 24, cost = 15 },
      [5] = { level = 30, cost = 25 },
      [6] = { level = 36, cost = 50 },
      [7] = { level = 42, cost = 75 },
      [8] = { level = 48, cost = 100 },
      [9] = { level = 54, cost = 125 },
      [10] = { level = 60, cost = 150 },
      [11] = { level = 70, cost = 175 },
    },
  },
  ["Nature Resistance"] = {
    active = false,
    families = { "ALL" },
    ranks = {
      [1] = { level = 20, cost = 5 },
      [2] = { level = 30, cost = 15 },
      [3] = { level = 40, cost = 45 },
      [4] = { level = 50, cost = 90 },
      [5] = { level = 60, cost = 105 },
    },
  },
  ["Poison Spit"] = {
    active = true,
    families = { "Serpent" },
    ranks = {
      [1] = { level = 15, cost = 5 },
      [2] = { level = 45, cost = 20 },
      [3] = { level = 60, cost = 25 },
    },
  },
  ["Prowl"] = {
    active = true,
    families = { "Cat" },
    ranks = {
      [1] = { level = 30, cost = 15 },
      [2] = { level = 40, cost = 20 },
      [3] = { level = 50, cost = 25 },
    },
  },
  ["Scorpid Poison"] = {
    active = true,
    families = { "Scorpid" },
    ranks = {
      [1] = { level = 8, cost = 10 },
      [2] = { level = 24, cost = 15 },
      [3] = { level = 40, cost = 20 },
      [4] = { level = 56, cost = 25 },
      [5] = { level = 64, cost = 29 },
    },
  },
  ["Screech"] = {
    active = true,
    families = { "Bat", "Carrion Bird", "Owl" },
    ranks = {
      [1] = { level = 8, cost = 10 },
      [2] = { level = 24, cost = 15 },
      [3] = { level = 48, cost = 20 },
      [4] = { level = 56, cost = 25 },
      [5] = { level = 64, cost = 29 },
    },
  },
  ["Shadow Resistance"] = {
    active = false,
    families = { "ALL" },
    ranks = {
      [1] = { level = 20, cost = 5 },
      [2] = { level = 30, cost = 15 },
      [3] = { level = 40, cost = 45 },
      [4] = { level = 50, cost = 90 },
      [5] = { level = 60, cost = 105 },
    },
  },
  ["Shell Shield"] = {
    active = true,
    families = { "Turtle" },
    ranks = {
      [1] = { level = 20, cost = 15 },
    },
  },
  ["Thunderstomp"] = {
    active = true,
    families = { "Gorilla" },
    ranks = {
      [1] = { level = 30, cost = 15 },
      [2] = { level = 40, cost = 20 },
      [3] = { level = 50, cost = 25 },
    },
  },
  ["Warp"] = {
    active = true,
    families = { "Warp Stalker" },
    ranks = {
      [1] = { level = 60, cost = 1 },
    },
  },
}

D.Families = {
  ["Bat"] = { "Bite", "Dive", "Screech" },
  ["Bear"] = { "Bite", "Claw" },
  ["Boar"] = { "Bite", "Charge", "Dash", "Gore" },
  ["Carrion Bird"] = { "Bite", "Claw", "Dive", "Screech" },
  ["Cat"] = { "Bite", "Claw", "Dash", "Prowl" },
  ["Crab"] = { "Claw" },
  ["Crocolisk"] = { "Bite" },
  ["Dragonhawk"] = { "Bite", "Dive", "Fire Breath" },
  ["Gorilla"] = { "Bite", "Thunderstomp" },
  ["Hyena"] = { "Bite", "Dash" },
  ["Nether Ray"] = { "Bite", "Dive" },
  ["Owl"] = { "Claw", "Dive", "Screech" },
  ["Raptor"] = { "Bite", "Claw", "Dash" },
  ["Ravager"] = { "Bite", "Dash", "Gore" },
  ["Scorpid"] = { "Claw", "Scorpid Poison" },
  ["Serpent"] = { "Bite", "Poison Spit" },
  ["Spider"] = { "Bite" },
  ["Sporebat"] = { },
  ["Tallstrider"] = { "Bite", "Dash" },
  ["Turtle"] = { "Bite", "Shell Shield" },
  ["Warp Stalker"] = { "Bite", "Claw", "Warp" },
  ["Wind Serpent"] = { "Bite", "Dive", "Lightning Breath" },
  ["Wolf"] = { "Bite", "Dash", "Furious Howl" },
}

D.CommonAbilities = {
  "Growl",
  "Cower",
  "Great Stamina",
  "Natural Armor",
  "Avoidance",
  "Cobra Reflexes",
  "Arcane Resistance",
  "Fire Resistance",
  "Frost Resistance",
  "Nature Resistance",
  "Shadow Resistance",
}

D.AbilityOrder = {
  "Growl",
  "Cower",
  "Bite",
  "Claw",
  "Gore",
  "Charge",
  "Dash",
  "Dive",
  "Prowl",
  "Furious Howl",
  "Screech",
  "Scorpid Poison",
  "Poison Spit",
  "Lightning Breath",
  "Fire Breath",
  "Thunderstomp",
  "Shell Shield",
  "Warp",
  "Great Stamina",
  "Natural Armor",
  "Avoidance",
  "Cobra Reflexes",
  "Arcane Resistance",
  "Fire Resistance",
  "Frost Resistance",
  "Nature Resistance",
  "Shadow Resistance",
}

-- Classic/TBC pet ability icon textures (Interface\\Icons\\...)
D.AbilityIcons = {
  ["Growl"] = "Interface\\Icons\\Ability_Physical_Taunt",
  ["Cower"] = "Interface\\Icons\\Ability_Druid_Cower",
  ["Bite"] = "Interface\\Icons\\Ability_Racial_Cannibalize",
  ["Claw"] = "Interface\\Icons\\Ability_Druid_Rake",
  ["Gore"] = "Interface\\Icons\\Inv_Weapon_ShortBlade_28",
  ["Charge"] = "Interface\\Icons\\Ability_Hunter_Pet_Boar",
  ["Dash"] = "Interface\\Icons\\Ability_Druid_Dash",
  ["Dive"] = "Interface\\Icons\\Spell_Shadow_BurningSpirit",
  ["Prowl"] = "Interface\\Icons\\Ability_Druid_Prowl",
  ["Furious Howl"] = "Interface\\Icons\\Ability_Hunter_Pet_Wolf",
  ["Screech"] = "Interface\\Icons\\Ability_Hunter_Pet_Owl",
  ["Scorpid Poison"] = "Interface\\Icons\\Ability_PoisonSting",
  ["Poison Spit"] = "Interface\\Icons\\Spell_Nature_CorrosiveBreath",
  ["Lightning Breath"] = "Interface\\Icons\\Spell_Nature_Lightning",
  ["Fire Breath"] = "Interface\\Icons\\Spell_Fire_Burnout",
  ["Thunderstomp"] = "Interface\\Icons\\Ability_ThunderClap",
  ["Shell Shield"] = "Interface\\Icons\\Ability_Hunter_Pet_Turtle",
  ["Warp"] = "Interface\\Icons\\Spell_Arcane_Arcane04",
  ["Great Stamina"] = "Interface\\Icons\\Spell_Nature_UnyeildingStamina",
  ["Natural Armor"] = "Interface\\Icons\\Spell_Nature_SpiritArmor",
  ["Avoidance"] = "Interface\\Icons\\Spell_Magic_LesserInvisibilty",
  ["Cobra Reflexes"] = "Interface\\Icons\\Spell_Nature_GuardianWard",
  ["Arcane Resistance"] = "Interface\\Icons\\Spell_Nature_StarFall",
  ["Fire Resistance"] = "Interface\\Icons\\Spell_Fire_FireArmor",
  ["Frost Resistance"] = "Interface\\Icons\\Spell_Frost_WizardMark",
  ["Nature Resistance"] = "Interface\\Icons\\Spell_Nature_ResistNature",
  ["Shadow Resistance"] = "Interface\\Icons\\Spell_Shadow_AntiShadow",
}
